############################################################
# +------------------------------------------------------+ #
# |                        EP-UHC                        | #
# +------------------------------------------------------+ #
############################################################

#Configurations des messages personnalisé lié au plugin
messages:

  # Message des victoires
  # - {team} correspond a la team ayant gagné
  win: "&c[&6EP-UHC&c] - &bL'équipe {team} &ba remporté la partie !"
  
  # Message de mort
  death: "&c[&6EP-UHC&c] - &9Vous &bêtes mort !"
  
  # Message de kill
  # - {killer} correspond au joueur ayant tué
  # - {victim} correspond au joueur ayant été tué
  kill: "&c[&6EP-UHC&c] - &9{victim} &best mort !"
  
  # Message lorsque le jeu est déjà lancé
  started: "&c[&6EP-UHC&c] - &bLe jeu est déjà lancé !"
  
  # Message d'arrivée sur le serveur
  # - {player} correspond au joueur ayant rejoint le serveur
  # - {nbPlayers} correspond au nombre de joueurs sur le serveur
  join: "&c[&6EP-UHC&c] - &9{player} &ba rejoint le serveur ! &7<{nbPlayers}/50>"
  reconnect: "&c[&6EP-UHC&c] - &9{player} &bs'est reconnecté"
  
  # Message de départ du serveur
  # - {player} correspond au joueur ayant rejoint le serveur
  quit: "&c[&6EP-UHC&c] - &9{player} &ba quitté le serveur !"
  
  # Message durant la periode d'invincibilité
  # - {timer} correspond au temps avant la fin de la periode
  GraceReminder: "&c[&6EP-UHC&c] - &bFin de la periode d'invincibilité dans &9{timer} &bsecondes"
  GraceEnd: "&c[&6EP-UHC&c] - &bFin de la periode d'invincibilité"
  
  
  # Message de lancement du jeu
  start: "&c[&6EP-UHC&c] - &bLancement du jeu. Veuillez patientez durant la téléportation"
  
  # Message durant la periode de farming
  # - {timer} correspond au temps avant le pvp
  FarmReminder: "&c[&6EP-UHC&c] - &bLe PvP sera activé dans &9{timer} &bminutes"
  
  # Message de début du pvp
  pvp: "&c[&6EP-UHC&c] - &9PVP &bactivé !"
  
  # Message si la partie n'est pas lancée
  stopped: "&c[&6EP-UHC&c] - &bIl n'y a pas de partie en cours !"

  # Message sur la bordure:
  # - {timer} correspond au temps avant la reduction de la bordure
  borderReminder: "&c[&6EP-UHC&c] - &bLa bordure se réduira dans &9{timer} &bminutes"
  borderReduction: "&c[&6EP-UHC&c] - &bLa bordure commence a se réduire"
  
#Configurations des timers personnalisé lié au plugin
timers:

  # Timer pour le début de l'uhc
  start: 10
  
  # Timer pour le pvp
  pvp: 20*60
  
  # Timer avant le depart de la bordure:
  timerBeforeBorder: 40
  
  # Temps de reduction de la bordure:
  borderReductionTime: 1800
  
 #Configuration de la bordure
border:
  # Timer pour le début de la réduction de la bordure (Attention, le timer est a initialiser en supposant que la periode de pvp vien de s'activer)
  start: 10  
  # Taille de la bordure (en bloc) (+- size)
  size: 1500.0
itemInterdit:
  DIAMOND_SWORD
  IRON_SWORD